### ISSUE TITLE
Support subject impersonation 

### ISSUE THREAD

**Issue by roger-lo** [jasonfriedland/httpie-asap-auth#7]
Current behaviour is for this to ignore the "sub" field. 

We just need to propagate this value through to support subject impersonation.

**Comment by jasonfriedland** [comment]
Hi @roger-lo , I'll take a look at this and create a PR for it. FYI the value used by the ASAP library falls back to the `iss` field if `sub` is unset.

**Comment by jasonfriedland** [comment]
https://github.com/jasonfriedland/httpie-asap-auth/pull/8

**Comment by roger-lo** [comment]
Awesome. Thanks @jasonfriedland!
